addons:
  ssh_known_hosts: li.rtdemo.in

before_install:
- openssl aes-256-cbc -K $encrypted_b8edb6da5ab0_key -iv $encrypted_b8edb6da5ab0_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

script:
- rsync -a --exclude=".git" --exclude=".travis.yml" --exclude="id_rsa.enc"
  . /tmp/gutenberg-supplements/
- ls -al /tmp/gutenberg-supplements

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet /tmp/gutenberg-supplements www-data@li.rtdemo.in:/var/www/rtcamp.li.rtdemo.in/app/src/wp-content/plugins/
  on:
    branch: master
